present_year = 4327
present_month = 10
present_day = 15

[[views]]
id = "public"
title = "World History (Public)"
tags_all = ["public"]
tick_scale = "century"
tick_spacing_px = 72
sort_direction = "desc"

[[views]]
id = "merrowgate"
title = "World History (Merrowgate)"
tags_any = ["public", "merrowgate"]
tick_scale = "decade"
tick_spacing_px = 300
sort_direction = "desc"
max_summary_lines = 6

[views.range]
last_years = 170


[[views]]
id = "elven"
title = "World History (Elven)"
tags_any = ["public", "araethilion", "sabriel"]
tick_scale = "century"
tick_spacing_px = 72
sort_direction = "desc"
max_summary_lines = 6

[views.range]
last_years = 3500

[[views]]
id = "elderholt"
title = "elderholt"
tags_any = ["public", "elderholt"]
tick_scale = "year"
tick_spacing_px = 20
sort_direction = "desc"
max_summary_lines = 8
hide_time_measurements = false

[views.range]
last_years = 100
